export const greetings = {
    morning: [
      "Good Morning, Chefs!",
      "Rise and Shine, Cooking Stars!",
      "Wake up, it's Cooking Time!",
      "A beautiful morning to cook!",
      "Morning glory in the kitchen!",
      "Start your day with a delicious recipe!",
      "Sunrise brings new cooking adventures!",
      "Embrace the morning flavors!",
      "Happiness begins in the kitchen!",
      "Good morning, Masterchefs!",
      "A fresh morning to try new recipes!",
      "New day, new cooking possibilities!",
      "Good morning, aspiring cooks!",
      "Time to whip up some morning delights!",
      "A joyful morning to experiment with flavors!",
      "Morning breeze, morning cuisine!",
      "May your morning be full of tasty creations!",
      "Good morning, kitchen artists!",
      "A flavorful start to the day!",
      "A delightful morning to savor recipes!",
      "Good morning, culinary explorers!",
      "A delightful breakfast awaits!",
      "Time to cook up a morning storm!",
      "Good morning to all cooking enthusiasts!",
      "Spice up the morning with culinary magic!",
      "A morning dedicated to deliciousness!",
      "Start your day with a culinary adventure!",
      "Morning inspiration for your kitchen!",
      "Embrace the morning's cooking challenges!",
      "Good morning and happy cooking!",
      // Add more morning greetings (at least 30)
      // ...
    ],
    brunch: [
      "Time for Brunch, Foodies!",
      "Enjoy your Brunch Delights!",
      "Brunch Time - Flavor Extravaganza!",
      "Delicious Brunch awaits your creativity!",
      "Brunching with Culinary Passion!",
      "A delightful brunch spread for you!",
      "Get inventive with your brunch recipes!",
      "A perfect mid-morning culinary treat!",
      "Brunching - Where flavors unite!",
      "Savor the magic of brunch cuisine!",
      "Enjoy a mouthwatering brunch adventure!",
      "Brunch - The Art of Culinary Fusion!",
      "Time to try something extraordinary for brunch!",
      "A brunch to cherish and savor!",
      "Treat yourself to a delicious brunch delight!",
      "Indulge in the wonders of brunch cuisine!",
      "Brunch - The perfect mix of taste and joy!",
      "Embrace the brunch vibes!",
      "A delightful brunch affair for food lovers!",
      "Unleash your brunch creativity!",
      "Good food, good company, and brunch!",
      "Sip and savor the flavors of brunch!",
      "Brunch - The culinary dance of flavors!",
      "Time for a culinary brunch masterpiece!",
      "Delight in a lavish brunch spread!",
      "Brunch - A symphony of taste and texture!",
      "The joy of brunch awaits your kitchen!",
      "Brunch - Where culinary dreams come true!",
      "A brunch to remember forever!",
      "Brunch - A journey of culinary bliss!",
      // Add more brunch greetings (at least 30)
      // ...
    ],
    lateMorning: [
      "Late Morning Cookery!",
      "Keep up the Good Cooking!",
      "Productive Morning in the Kitchen!",
      "Cooking mode on - Flavor Alert!",
      "Focused and Ready to Cook!",
      "Making Progress this Late Morning!",
      "Efficiency in the Late Morning Kitchen!",
      "Crushing Culinary Goals before Noon!",
      "Late Morning Cooking Mastery!",
      "Late Morning Hustle in the Kitchen!",
      "Late Morning Magic - Cook with Passion!",
      "Getting things done in the Kitchen!",
      "Late Morning Success on Your Plate!",
      "Good work in the late morning - Bon Appétit!",
      "Progress in the late morning delights!",
      "Late Morning Goals achieved on a Platter!",
      "Cooking with Determination this Late Morning!",
      "Late Morning Culinary Brilliance!",
      "Thriving in the Late Morning Kitchen!",
      "Late Morning Accomplishments in your Cuisine!",
      "Late Morning Wins for Culinary Enthusiasts!",
      "Late Morning Motivation - Cooking Inspiration!",
      "Making Culinary Strides this Late Morning!",
      "Late Morning Focus - Flavors and More!",
      "A Successful Late Morning Cooking Session!",
      "Cooking with Passion in the Late Morning!",
      "A Productive Late Morning in the Kitchen!",
      "Late Morning Cooking Routine - Perfectly Timed!",
      "Late Morning Culinary Excellence!",
      "Late Morning Achievements on the Menu!",
      // Add more late morning greetings (at least 30)
      // ...
    ],
    lunch: [
      "Lunch Time - Bon Appétit!",
      "Enjoy your Flavorful Lunch!",
      "Delicious lunch awaits your taste buds!",
      "Lunch Break with Culinary Joy!",
      "A delightful lunch to savor!",
      "Taste the Essence of Lunch Cuisine!",
      "Savoring a Tasty Lunch!",
      "Lunchtime Happiness on your Plate!",
      "Lunchtime Joy with Culinary Love!",
      "Lunchtime with Great Flavors!",
      "A Nourishing Lunch to Relish!",
      "A lunchtime feast for Culinary Enthusiasts!",
      "A Lunch to Remember Forever!",
      "Enjoying a Hearty Lunch!",
      "Lunchtime Celebrations in the Kitchen!",
      "A Delicious Lunch Spread for You!",
      "Lunch and Laughter with Loved Ones!",
      "Lunchtime Energy Boost with Culinary Magic!",
      "Enjoying the Culinary Delights of Lunch!",
      "Tasty Lunch Choices for Food Lovers!",
      "A Fulfilling Lunch Experience!",
      "Lunchtime Delights for All!",
      "Tasty and Nutritious Lunch - Foodie Delight!",
      "A Lunch Break Well-Deserved!",
      "Savoring Every Flavorful Lunch Bite!",
      "Lunchtime with Good Vibes!",
      "Relishing the Flavors of Lunch Cuisine!",
      "Lunchtime - A Culinary Symphony!",
      "A Lunch Gathering to Enjoy!",
      "A Lunch to Recharge and Unwind!",
      // Add more lunch greetings (at least 30)
      // ...
    ],
    afternoonTea: [
      "Afternoon Tea Time, Tea Lovers!",
      "Enjoy your Afternoon Tea!",
      "Sip and Savor - Afternoon Tea Magic!",
      "Afternoon Tea - A Blend of Culinary Joy!",
      "Afternoon Tea Time - Flavorful Moments!",
      "A Delightful Afternoon Tea Spread for You!",
      "Get Cozy with Afternoon Tea Bliss!",
      "An Afternoon of Tea and Culinary Harmony!",
      "A Tea Break to Cherish and Savor!",
      "Indulge in the Magic of Afternoon Tea!",
      "Savoring the Afternoon Tea Flavors!",
      "A Perfect Afternoon Tea Affair!",
      "Treat Yourself to Afternoon Tea Delights!",
      "Embrace the Joy of Afternoon Tea!",
      "Time to Relax with Afternoon Tea!",
      "Afternoon Tea - Sip and Smile!",
      "Savor Every Moment of Afternoon Tea!",
      "Afternoon Tea - The Art of Tea Blending!",
      "A Calming Afternoon Tea Experience!",
      "An Afternoon Tea Symphony of Flavors!",
      "A Nourishing Afternoon Tea Treat!",
      "Tea Time Magic - Afternoon Edition!",
      "Afternoon Tea - Where Taste Meets Serenity!",
      "Sip and Savor the Beauty of Afternoon Tea!",
      "A Moment of Tranquility with Afternoon Tea!",
      "Tea Time Bliss - Afternoon Style!",
      "An Afternoon Tea Delight to Remember!",
      "Afternoon Tea Pleasures for All!",
      "A Cozy Afternoon Tea Experience!",
      "Afternoon Tea - A Cup of Culinary Joy!",
      // Add more afternoon tea greetings (at least 30)
      // ...
    ],
    snack: [
      "Time for a Snack, Foodies!",
      "Healthy Snacking - Happy Cooking!",
      "Enjoy your Snack Break!",
      "Craving a Quick Bite!",
      "Tasty Snacks on the Go!",
      "Snack Time Delight - Culinary Bliss!",
      "A Treat for Snack Time Enthusiasts!",
      "Nourishing Snack Choices for You!",
      "A Satisfying Snack Break Awaits!",
      "Snacking with a Smile - Culinary Happiness!",
      "Healthy and Delicious Snacks to Savor!",
      "Savoring Snack Time Moments!",
      "A Snack for Every Culinary Craving!",
      "Snack Time with Variety and Flavor!",
      "Snacks to Keep You Energized!",
      "Treat Yourself to a Snack Delight!",
      "Snacking Made Joyful - Culinary Magic!",
      "Satisfying Snack Choices for Foodies!",
      "A Delightful Snack to Enjoy!",
      "Snack Time Made Special - Culinary Love!",
      "Snacking with Happiness and Flavor!",
      "Healthy Bites for Snack Time Happiness!",
      "A Snack Break Well-Deserved!",
      "Enjoying Every Snack Bite!",
      "Snack Time - Happy Time with Food!",
      "A Delicious Snack Treat for You!",
      "Savoring Every Snack Moment!",
      "A Snack to Brighten Your Day!",
      "Snack Time with Good Vibes!",
      "Savor the Flavors of Snacks!",
      // Add more snack greetings (at least 30)
      // ...
    ],
    eveningChores: [
      "Evening Chores - Bon Appétit!",
      "Get Things Done - Evening Kitchen Style!",
      "Productive Evening in the Kitchen!",
      "Taking Care of Evening Culinary Tasks!",
      "Efficiency in the Evening Cooking Zone!",
      "A Productive Evening Awaits - Culinary Success!",
      "Late Evening - Cooking Goals and More!",
      "Evening Kitchen Hustle - Culinary Brilliance!",
      "Evening Culinary Magic - Achieving Success!",
      "Evening Accomplishments in the Kitchen!",
      "A Successful Evening in Your Cuisine!",
      "Completing Evening Culinary To-Dos!",
      "Evening Wins for Culinary Enthusiasts!",
      "Evening Kitchen Motivation - Cooking Inspiration!",
      "Making Culinary Strides this Evening!",
      "Evening Focus - Flavors and More!",
      "A Successful Evening Cooking Routine!",
      "Evening Culinary Excellence and Joy!",
      "Thriving in the Evening Kitchen!",
      "Evening Kitchen Celebrations!",
      "A Delicious Evening Culinary Experience!",
      "Evening Culinary Goals for Food Lovers!",
      "Evening Culinary Magic - A Symphony of Flavors!",
      "Evening Kitchen Creativity - Let's Cook!",
      "Evening Kitchen Mastery - Flavors Unite!",
      "Evening Cooking Adventures - Culinary Delights!",
      "Evening Kitchen Bliss - Culinary Treasures!",
      "Evening Culinary Accomplishments!",
      "Evening Kitchen Wins for Foodie Delights!",
      // Add more evening chores greetings (at least 30)
      // ...
    ],
    dinner: [
      "Let's Get Dinner Ready!",
      "Dinner Time - Bon Appétit!",
      "Enjoy your Flavorful Dinner!",
      "Delicious Dinner Awaits Your Palate!",
      "Dinner with Family and Culinary Love!",
      "A Delightful Dinner Spread for You!",
      "Savoring a Tasty Dinner Affair!",
      "Dinner Time Happiness on Your Plate!",
      "Dinner Time Joy with Loved Ones!",
      "A Dinner Feast to Remember!",
      "Treat Yourself to a Delicious Dinner!",
      "Dinnertime Happiness - Culinary Bliss!",
      "Dinner Time with Culinary Magic!",
      "A Nourishing Dinner to Relish!",
      "A Dinner to Cherish and Savor!",
      "Enjoying a Hearty Dinner Affair!",
      "Dinner and Laughter with Loved Ones!",
      "Dinner Time Energy Boost with Culinary Love!",
      "Enjoying the Culinary Delights of Dinner!",
      "Tasty Dinner Choices for Foodie Delight!",
      "A Fulfilling Dinner Experience!",
      "Dinner Delights for All - Culinary Joy!",
      "Tasty and Nutritious Dinner - Flavor Extravaganza!",
      "A Dinner Break Well-Deserved!",
      "Savoring Every Flavorful Dinner Bite!",
      "Dinner Time with Good Vibes!",
      "Relishing the Flavors of Dinner Cuisine!",
      "Dinner Time - A Culinary Symphony!",
      "A Dinner Gathering to Enjoy and Savor!",
      "A Dinner to Recharge and Unwind!",
      // Add more dinner greetings (at least 30)
      // ...
    ],
    nightSnack: [
      "Night Snackers Unite!",
      "Late-Night Cravings - Culinary Joy!",
      "Enjoy a Midnight Snack Delight!",
      "Treat Yourself to a Nighttime Snack!",
      "Savoring Late-Night Munchies - Culinary Love!",
      "A Late-Night Treat for You!",
      "Midnight Munchies - Let's Cook!",
      "Nighttime Indulgence - Culinary Bliss!",
      "Late-Night Cravings Met with Flavorful Snacks!",
      "A Late-Night Snack to Savor!",
      "Late-Night Nibbles - Flavor Extravaganza!",
      "Nighttime Munching with Culinary Delight!",
      "Late-Night Snacking Made Special!",
      "A Night Owl's Favorite Time - Snack Time!",
      "Late-Night Snacks - Enjoy the Magic!",
      "A Late-Night Snack to Brighten Your Night!",
      "Late-Night Snacking with Good Vibes!",
      "Savoring Every Late-Night Snack Bite!",
      "Late-Night Snacking - A Culinary Symphony!",
      "A Late-Night Snack Affair for Foodies!",
      "Late-Night Snacks to Satisfy Your Cravings!",
      "Late-Night Snacking Bliss - Culinary Magic!",
      "A Night of Culinary Nighttime Delights!",
      "Late-Night Snacking - Savor and Enjoy!",
      "Late-Night Nibbles - A Moment of Delight!",
      "Nighttime Treats to Savor and Relish!",
      "Late-Night Snacks with Culinary Love!",
      "A Late-Night Snack to Remember!",
      "Late-Night Nibbles - A Feast for the Senses!",
      "Late-Night Snacking Bliss - Taste the Magic!",
      // Add more late-night snack greetings (at least 30)
      // ...
    ],
    timeToRelax: [
      "Time to Relax and Unwind!",
      "Culinary Relaxation Time - Enjoy!",
      "Savoring the Joy of Culinary Relaxation!",
      "Relax and Recharge with Culinary Bliss!",
      "A Moment of Relaxation with Culinary Magic!",
      "Take a Break and Enjoy the Culinary Delights!",
      "Relaxation Mode On - Culinary Style!",
      "Culinary Comforts for Relaxing Moments!",
      "A Moment to Savor and Embrace Culinary Relaxation!",
      "Relax with Delicious Culinary Creations!",
      "Take a Breath and Savor the Culinary Calm!",
      "Enjoy the Serenity of Culinary Relaxation!",
      "A Moment of Culinary Bliss - Relax and Enjoy!",
      "Relaxing with Culinary Treasures on the Menu!",
      "A Culinary Break to Recharge and Savor!",
      "Savoring Every Relaxing Culinary Moment!",
      "Culinary Delights for Relaxation and Joy!",
      "Take Time to Relax with Culinary Love!",
      "Savoring the Moments of Culinary Calm!",
      "Culinary Relaxation - A Moment of Delight!",
      "A Time to Embrace Culinary Relaxation!",
      "Take a Break and Savor the Culinary Serenity!",
      "Relaxing with Culinary Wonders and Delights!",
      "A Moment of Culinary Relaxation to Remember!",
      "Culinary Comforts for Relaxing Moments!",
      "Enjoying the Peace of Culinary Relaxation!",
      "Savoring Culinary Relaxation with a Smile!",
      "Relax and Enjoy the Culinary Treasures!",
      "A Moment of Culinary Relaxation - Taste the Magic!",
      "Culinary Delights for Relaxation and Joy!",
      // Add more relaxation greetings (at least 30)
      // ...
    ],
    goodEvening: [
      "Good Evening, Culinary Stars!",
      "Evening Bliss in the Kitchen!",
      "A Culinary Evening to Remember!",
      "Enjoy the Magic of Evening Cuisine!",
      "Good Evening, Food Enthusiasts!",
      "An Evening of Culinary Delights!",
      "Savoring the Joy of Evening Cuisine!",
      "Good Evening, Masterchefs!",
      "A Flavorful Evening to Cook and Enjoy!",
      "Evening Culinary Magic - Bon Appétit!",
      "Good Evening, Aspiring Cooks!",
      "An Evening of New Culinary Adventures!",
      "Evening Flavors to Savor and Enjoy!",
      "Good Evening, Culinary Explorers!",
      "A Culinary Evening Full of Delight!",
      "Evening Joy with Culinary Love!",
      "Good Evening, Kitchen Artists!",
      "An Evening of Culinary Artistry!",
      "Evening Pleasures for Food Lovers!",
      "Good Evening, Cooking Enthusiasts!",
      "A Delightful Evening to Try New Recipes!",
      "Evening Cooking - A Journey of Flavor!",
      "Good Evening, Culinary Adventurers!",
      "An Evening of Flavorful Surprises!",
      "Evening Time to Cook with Passion!",
      "Good Evening, Culinary Dreamers!",
      "A Culinary Evening of Dreams and Wonders!",
      "Evening Culinary Adventures with Loved Ones!",
      "Good Evening, Flavorsome Souls!",
      "An Evening of Culinary Creativity!",
      // Add more good evening greetings (at least 30)
      // ...
    ],
    lateEveningFun: [
      "Late Evening Fun - Culinary Style!",
      "Embrace the Late Evening Magic!",
      "A Night of Culinary Late Evening Wonders!",
      "Late Evening - Time for Culinary Fun!",
      "Enjoy the Late Evening Culinary Delights!",
      "A Late Evening of Culinary Merriment!",
      "Late Evening Bliss in the Kitchen!",
      "A Culinary Late Evening to Remember!",
      "Late Evening Adventures with Flavor!",
      "Late Evening Culinary Joy - Bon Appétit!",
      "Late Evening Fun for Food Lovers!",
      "A Late Evening of Culinary Surprises!",
      "Late Evening Culinary Magic to Savor!",
      "Late Evening Culinary Dreams - Let's Cook!",
      "Late Evening Flavors to Embrace!",
      "Late Evening Fun with Culinary Love!",
      "Late Evening Delights to Relish!",
      "Late Evening Culinary Celebrations!",
      "Late Evening Culinary Joy for All!",
      "Late Evening Culinary Adventure Awaits!",
      "Late Evening Culinary Creativity - Let's Cook!",
      "Late Evening Kitchen - A Time of Culinary Delight!",
      "Late Evening Culinary Inspiration - Bon Appétit!",
      "Late Evening Culinary Treats for You!",
      "Late Evening Culinary Happiness - Taste the Magic!",
      "Late Evening Culinary Magic with Loved Ones!",
      "Late Evening Culinary Flavors - A Symphony of Taste!",
      "Late Evening Culinary Treasures to Savor!",
      "Late Evening Culinary Memories to Cherish!",
      // Add more late evening fun greetings (at least 30)
      // ...
    ],
    midnightSnack: [
      "Midnight Snack Cravings!",
      "A Midnight Culinary Treat to Savor!",
      "Midnight Munchies - Let's Cook!",
      "Late-Night Indulgence - Culinary Bliss!",
      "Enjoy a Midnight Snack Delight!",
      "Savoring Late-Night Culinary Magic!",
      "Midnight Bites - Flavor Extravaganza!",
      "A Late-Night Culinary Adventure!",
      "Late-Night Culinary Delights to Relish!",
      "Midnight Munching with Culinary Love!",
      "A Late-Night Snack to Brighten Your Night!",
      "Late-Night Nibbles - A Moment of Delight!",
      "A Midnight Snack to Remember!",
      "Late-Night Snacking Bliss - Taste the Magic!",
      "Midnight Munchies for Food Lovers!",
      "A Midnight Snack Affair to Enjoy!",
      "Late-Night Snacks - Enjoy the Magic!",
      "Midnight Culinary Joy to Cherish!",
      "Late-Night Snacks - Savor and Enjoy!",
      "Midnight Munchies - A Feast for the Senses!",
      "Late-Night Snacking Bliss - Culinary Magic!",
      "A Moment of Culinary Midnight Delight!",
      "Late-Night Snacking - A Culinary Symphony!",
      "A Late-Night Snack to Brighten Your Night!",
      "Late-Night Nibbles - A Moment of Delight!",
      "A Midnight Snack to Remember!",
      "Late-Night Snacking Bliss - Taste the Magic!",
      "Midnight Munchies for Food Lovers!",
      "A Midnight Snack Affair to Enjoy!",
      "Late-Night Snacks - Enjoy the Magic!",
      "Midnight Culinary Joy to Cherish!",
      "Late-Night Snacks - Savor and Enjoy!",
      // Add more midnight snack greetings (at least 30)
      // ...
    ],
  };